### ISSUE TITLE
Preferred Editor

### ISSUE THREAD

**Issue by okwolf** [spatialillusions/milsymbol#100]
Which editor/IDE do you currently use to edit the JavaScript source files? I know among the free tools [Atom](https://atom.io) used to be the preferred tool of choice for text editors but personally I'm partial to the new kid on the block from Microsoft: [VS Code](https://code.visualstudio.com). It has better support for JavaScript and git built in, and plugins for everything else I've needed so far including ES Lint/Prettier to keep the quality/formatting of my code correct in real time. Plus the development on it has been very active and constantly improving while Atom seems somewhat stagnant lately.

If you're interested in using VS Code, or at least not otherwise bothered, I would like to commit some files I have locally that provide a launch configuration for running the tests in milsymbol with debugging support in your editor as well as some general config items for ES Lint/Prettier/etc. If you're not OK with that, then I'd like to add an ignore for these files so they won't keep showing up as changes and might accidentally get commited.

**Comment by spatialillusions** [comment]
I have historically used BBEdit, but a week ago or so I tried out VS Code and really like it. I have set it up with Prettier (format on save) and ESLint. 
If it is a limited number of files I think we could keep them in the repository to make it easier for other that want to contribute. If you update Contributing.md with information about how to use VS Code you can commit the files.

**Comment by okwolf** [comment]
Pull request #102 has an initial pass at this.
