### ISSUE TITLE
Customizing Symbol Output

### ISSUE THREAD

**Issue by enorton** [spatialillusions/milsymbol#101]
I think it would be useful to be able to customize the toSvg() or toCanvas() to only include certain fields in the output. For example, sometimes its nice to only have the graphic symbol portion in some views without the outside text fields and for other views you might want all available data in the symbol. Another customization would be size. 

Of course, the simple solution is to create two symbols with a subset of the same data, but seems more tidy to have one object with customized output.

**Comment by enorton** [comment]
I'm pro at finding stuff after I post an issue... 

Setting infoFields to false would get me what I want I believe.

**Comment by spatialillusions** [comment]
I was just replying that. ;-) 
Let me know if there is anything more you need to do and I'll look into it.
I'll close this and you can reopen it if you need to do anything more.

**Comment by enorton** [comment]
So we find ourselves in a situation where we turn off infoFields for some renders of the icon because they are used in a tree view and don't want the potential text clutter. However, Special Headquarters is still useful to be rendered in that situation as its rendered inside the icon frame and we've had cases where using it allows us to make a custom icon not in the standards. Unfortunately for our situation, it's either all on or all off. It would be handy to have a "displayFields" option where you can select which info fields would be displayed. Or allowFramedInfoFields true/false, to render any infoFields contained within the frame (unsure if there are others).  Or perhaps there is an existing option I'm not considering yet.
