### ISSUE TITLE
Break icon parts into several files

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#104]
The big file containing all icon parts should be broken into several smaller files that are loaded when needed. This already works for tactical point symbols and should be done in some similar way for other areas.

This case is for keeping track of changes that are made for other areas.

**Comment by okwolf** [comment]
This issue is referring to /src/ms/iconparts.js, correct?

**Comment by spatialillusions** [comment]
That is correct, as you can see src/iconparts/signals-intelligence.js is now a separate part. The problem here is to figure out what part that only are used in one part of the library. I think sea mines would be a good part to break out next.

**Comment by spatialillusions** [comment]
Another thing to be good to know here, there is an undocumented property... (I know, I'm a bad person I really should have documented this...)
https://github.com/spatialillusions/milsymbol/blob/master/src/symbol/setoptions.js#L61
So that if you set `ms._debug = true;` the library will log to the console if any symbol building block is missing. I had an idea of adding this to the big html documents that are rendering all symbols to see if anything was broken. Also this is something I have thought about adding to the tests...

**Comment by okwolf** [comment]
@spatialillusions is this done, or is there still more work to split up https://github.com/spatialillusions/milsymbol/blob/ce1afb3a0b00f16d9fdb9db9d938d188d6f95add/src/iconparts/iconparts.js?

**Comment by spatialillusions** [comment]
Yes there should be some more splits done, some parts are easy and some parts are a bit more tricky. 
Mine-warfare should be quite easy to break out. 
And then there should be a split between Air, Ground, Sea at least. At the moment there are some parts that are reused from Air into Ground and so on, but this should be updated so that they are independent.
At the moment you can sort of choose what SIDC parts you are going to import, but you will always get the big iconspart file in the build, the idea here is to limit what parts are imported and get a smaller library if you are building a system that only will handle ships or airplanes.

**Comment by spatialillusions** [comment]
Will close this and open up a new issue if I feel that we should break up ground.js inte smaller parts.
