### ISSUE TITLE
Use yarn instead of npm in documentation

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#107]
We should recommend using yarn instead of npm because of security reasons. This will only be a documentation change since everything already works with yarn.

**Comment by okwolf** [comment]
I've been using yarn myself, but I noticed you haven't committed a yarn.lock. Did you want to ignore that file?

On a side note, npm 5 has incorporated some of the features of yarn so I'm not sure if eventually yarn will become OBE at some point.

**Comment by spatialillusions** [comment]
I haven't had time to look anything more into this, so there is not done anything to use yarn instead of npm. The thing that I liked about yarn was that it didn't run code in modules when they were installed in the same way as nmp do (did???). I know how paranoid military people can be, so that was the reason for moving to yarn instead. If it works in the same way in npm now, this could simply be ignored.

**Comment by okwolf** [comment]
I'm not sure about the code in modules, but the features that made it back into the latest npm are performance improvements with an offline cache, deterministic builds (total control over what code is used in the build), and stronger integrity checks (sha512 for new packages).

**Comment by spatialillusions** [comment]
Just throwing in a link to the yarn.lock file to have a look at when doing this... https://yarnpkg.com/lang/en/docs/yarn-lock/

**Comment by spatialillusions** [comment]
Won't fix at the moment. Please reopen if yarn support is needed.
