### ISSUE TITLE
Quantity text modifier cut off

### ISSUE THREAD

**Issue by canadajebus** [spatialillusions/milsymbol#108]
When adding a "Quantity" text modifier the number/text is cut off if it exceeds the width of the icons frame. When another text modifier is added that is positioned to the left or right of the icons frame, such as Location (left side), it extends the bounds of the symbols and will show the cut off portion of the Quantity text.

This is pretty minor imo, I don't see someone adding a quantity with that many characters, but ya never know.  I just discovered this by accident when testing the constraints on my input fields.

**Comment by spatialillusions** [comment]
Should be a quick fix to set x1 and x2 here after calculating the string width using strWidth.
https://github.com/spatialillusions/milsymbol/blob/master/src/symbolparts/textfields.js#L286
Feel free to make a pull, otherwise I will look into it when I have time.

**Comment by spatialillusions** [comment]
Or it should be added here, and in the similar expression a few lines down. https://github.com/spatialillusions/milsymbol/blob/master/src/symbolparts/textfields.js#L418

**Comment by canadajebus** [comment]
This actually resolves itself when using the ms.addSymbolPart, extention squareIcon() that is used in your ArcGIS3d example.
