### ISSUE TITLE
wrong symbol

### ISSUE THREAD

**Issue by Codingboy** [spatialillusions/milsymbol#109]
When calling
`return new ms.Symbol("10231000111211001000");`
instead of a "C2" modifier1, a "Y" modifier1 is displayed
[is](https://www.dropbox.com/s/ewb3xioffkceecn/10231000111211001000_is.png?dl=0) generated by milsymbol 1.1.0
[should](https://www.dropbox.com/s/6y5nclug1hwj4wo/10231000111211001000_should.png?dl=0) generated by [Symbol identification code explorer](http://explorer.milsymb.net/#/explore/)

The symbol should be a simulated infantry command and control team.
Am I doing something wrong?

**Comment by Codingboy** [comment]
maybe in [iconparts.js](https://github.com/spatialillusions/milsymbol/blob/master/src/ms/iconparts.js) line 1937 needs to be switched?
`icn["GR.M1.COMMAND AND CONTROL"] = _STD2525 ? textm1("Y") : textm1("C2");`

**Comment by spatialillusions** [comment]
I found it and you were sort of correct, the problem was that it was used in S*G*UCVRUC as well, and in that case it should be Y in 2525 and C2 in APP6. 
I have a plan to do a bigger work on many of the symbol parts in a few weeks time to make them even more modular. Please let me know if you find any more errors.

**Comment by Codingboy** [comment]
Thank you! I think I will need to play around with some symbols in like 2 months. Sure I will call back if I find other things.

**Comment by spatialillusions** [comment]
You can compare the standard with the symbol renderings here: (The documents are also included with the library.)
http://spatialillusions.com/milsymbol/docs/milsymbol-2525d-svg.html
Also let me know if there are any more functionality that you think should be added to the library.

**Comment by Codingboy** [comment]
To be honest. I think the API is pretty straight forward.
