### ISSUE TITLE
centering tactical symbol

### ISSUE THREAD

**Issue by Codingboy** [spatialillusions/milsymbol#110]
I dont know if this is more a question or a featurerequest...
You told me to ask for features if I have something in mind, so here we go:
When creating an infantry symbol the X in the frame is the center, when also setting a direction the center of the image is lower, when adding a type the center is on the left and so on. Is there a possibillity to keep the tactical symbol in the center no matter what diection or other texts are displayed? This might be used as additional parameter {centered: true}

**Comment by spatialillusions** [comment]
Usually you use getAnchor() or getOctagonAnchor() to get information about where the center is located. This makes it possible for the generated image to be as small as possible.

However if you need a square icon, this can be done with a small extra function, this is shown in the ArcGIS example:

```js
// Since we can define a insertion point for a IconSymbol3DLayer in ArcGIS JS API,
// and we can't really handle non square icons, we have to go around the problem by 
// making the icons square around the anchor point, so we add a custom extension to 
// milsymbol to do that.
ms.addSymbolPart(
  function squareIcon() {
    var gbbox = new ms.BBox();
    if (this.square) {
      var anchor = { x: 100, y: 100 };
      if (this.properties.headquarters) {
        anchor = {
          x: this.properties.baseGeometry.bbox.x1,
          y: this.properties.baseGeometry.bbox.y2 + ms.getHqStafLength()
        };
      }
      var maxx = Math.max(anchor.x - this.bbox.x1, this.bbox.x2 - anchor.x);
      var maxy = Math.max(anchor.y - this.bbox.y1, this.bbox.y2 - anchor.y);
      var max = Math.max(maxx, maxy);
      gbbox.x1 = anchor.x - max;
      gbbox.y1 = anchor.y - max;
      gbbox.x2 = anchor.x + max;
      gbbox.y2 = anchor.y + max;
    }
    return { pre: [], post: [], bbox: gbbox };
  }
);
```

**Comment by Codingboy** [comment]
Thank you, this might solve my issue.
