### ISSUE TITLE
Angular Example Console error  

### ISSUE THREAD

**Issue by jm4github** [spatialillusions/milsymbol#112]
The application has a console error when try to use it the first time, In other words, trying to go from https://spatialillusions.com/milsymbol/examples/index.html to https://spatialillusions.com/milsymbol/examples/example.html#angular you can see a console error  GET https://spatialillusions.com/milsymbol/examples/angular/%7B%7Bcode%7D%7D 404 (Not Found).

Using the application in my local machine, I have a similar issue: 
Failed to load resource: net::ERR_FILE_NOT_FOUND %7B%7Bcode%7D%7D

Also, I've modified the code not using a directive with a method like this:
JS:
function getImageFromMilsymbolLibrary(sic) {
            var symbol = new ms.Symbol(sic, { size: 40 || 20 });
            return symbol.toDataURL();
        }
$scope.sic = getImageFromMilsymbolLibrary("SFG-UCIZ---B"); 
HTML:
<...'img width="100px" height="62px" class="symbol-sm" src="{{sic}}'..../>

Unfortunately, I have the same error. The library works fine for me and I can see the symbols but I would like to remove thi anoying error message. I think it's a problem with in milsymbol.js

Any ideas? Thanks in advance

**Comment by spatialillusions** [comment]
I think the error comes from that the web-browser tries to load the template before the src has been replaced with the output from milsymbol. 
(%7B%7Bcode%7D%7D is the same as {{code}} in the src attribute of the img template.)
As far as I can tell this has nothing to do with milsymbol is something caused by angular, and I'm not sure if there is a workaround to solve this.

**Comment by spatialillusions** [comment]
I think I found a solution. If the template uses ng-src instead of src, things will work as expected. I have updated the master branch with this change. 
You can close this issue if this solves you problem as well.

**Comment by kjellmf** [comment]
You are absolutely right @spatialillusions . It should be `ng-src` instead of `src`.

**Comment by jm4github** [comment]
Awesome, you are very kind, the ng-src solves the issue. Thank you very much for your quick response.
