### ISSUE TITLE
MIL-STD2525D does not seem to show unit altitude

### ISSUE THREAD

**Issue by jkhoel** [spatialillusions/milsymbol#113]
Currently only tested on the unit generator. However, according to MIL-STD2525D p.143 Figure C-III and Table C-II altitude should show (along with measurement unit) 

[Screenshot from the unit generator here](http://imgur.com/a/hRXie)

**Comment by spatialillusions** [comment]
You are correct, there is an error on line 334 in src/symbolparts/textfields.js. If you are able to do a pull please do so, otherwise I'll fix it when I have time.

/Måns

Web: www.spatialillusions.com
Twitter: spatialillusion
Mail: mans.beckman@spatialillusions.com

**Comment by spatialillusions** [comment]
Fixed and made a new release.
