### ISSUE TITLE
Add Typings for VS Code Intellisense

### ISSUE THREAD

**Issue by thw0rted** [spatialillusions/milsymbol#130]
I noticed that while you suggest using VS Code as an editor in the contribution guidelines, you don't provide a Typescript definition of the library to help with Intellisense.  The result is that using milsymbol directly from NPM gives no Intellisense.  Try this:

1. Make a new project directory and run `npm init`, accepting all defaults
1. `npm install --save milsymbol`
1. Make a file `index.js` with the contents `const ms = require("milsymbol")`
1. Type `ms.` and wait for autocomplete to appear

There's nothing populated, though the library loads fine.  For example, add `var sym = new ms.Symbol('SFG-UCI----D', {size:30}); console.log(sym.width, sym.height);`, then run `node index.js` and it works fine.

Other libraries in NPM help by providing a Typings definition in the distro.  I don't really speak Typescript but I managed to come up with [a simple example](https://gist.github.com/thw0rted/0b9cfa1c6c8cf068df17a622b3cbdca2) that populates Intellisense based on your documentation.  I'm not sure it's complete, and it might be terrible Typescript, but it solves the immediate problem described above.  You can test by dropping `index.d.ts` in `node_modules/milsymbol`.

**Comment by spatialillusions** [comment]
Great suggestion, I haven't worked that much with intellisense and will have a look at your file. I did a quick google and found that things might work with JSDoc annotations in the code directly and that might be a way to make it easy to maintain.  If anyone would like to help out with this it would be much appreciated.

**Comment by thw0rted** [comment]
I use JSDoc to annotate my code but I'm not sure how to set up your `package.json` such that VS will read the unminified code (with the JSDoc comments) while Webpack will include the minified version, all with a single `import ms from "milsymbol"`.    Maybe it's doable?

I also use an NPM package called `mgrs` -- this uses JSDoc annotations, and it works great, but their build process does not include minification before publishing the package.  Now, your NPM package is more like, for example, `moment.js`, which is distributed minified and includes a `.d.ts` file.

All that to say: I'm still reading about how Intellisense works.  I'd love to get the most robust possible Intellisense feedback -- comments describing what a function does, what to pass for parameters, etc. -- but I'm not sure how to do that, other than distributing unminified code with the JSDoc comments intact.  I'll comment here if I find out more.

**Comment by spatialillusions** [comment]
There should be a way to set up a build process that builds the `.d.ts` from JSDoc annotations in the code. This would minimize to forget to update the `.d.ts` file when the code is updated. Any information about this would be welcome.

**Comment by spatialillusions** [comment]
Had a look at your sample and it looks good! Wouldn't mind if you made a pull with it. The only thing that we need to look into is that Symbol and setOptions now can take any number of arguments with symbol options (and that the first argument can be either a string or a symbol options object), not sure how to define that in ts, but should be possible in some way.

**Comment by thw0rted** [comment]
If you want to try automated generation I found [this project](https://github.com/englercj/tsd-jsdoc) but it's not very popular.  Ideally it would be possible to pass the (unminified, JSDoc-annotated) JS source directly to VSCode, while Webpack uses the pre-compiled version -- maybe this could be accomplished using separate `package.json`'s `browser` and `main` values?  I don't know enough VSCode internals to help with that, might be worth asking on the VSCode GitHub tracker.

In the meantime, I'm putting together a PR for the basic typings file -- I'm going to need help with ColorMode, which isn't really explained in the docs.

**Comment by thw0rted** [comment]
[PR is in](https://github.com/spatialillusions/milsymbol/pull/131).

**Comment by spatialillusions** [comment]
I merged the pull and made some minor fixes, now it looks like things are working, but would be great if someone with more knowledge about typescript definitions had a look.

**Comment by spatialillusions** [comment]
Since most of this is working now I think we close it until we want to do any further changes.
