### ISSUE TITLE
Move to Rollup instead of Webpack

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#145]
Should at least investigate if we can move to Rollup instead of Webpack. Like Webpack mentions on their blog, Webpack is great for sites, but Rollup might be better for libraries.
https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

If anyone has any experience or would like to help out, please comment here.

**Comment by okwolf** [comment]
@spatialillusions take a gander @ #146

**Comment by spatialillusions** [comment]
Awesome work! I will have a look as soon as possible, kind of deep into building test renderings for APP-6 D at the moment. 
Did you find any reason for not moving to rollup?

**Comment by okwolf** [comment]
> @spatialillusions Did you find any reason for not moving to rollup?

Nope, and I'm already using rollup on all my own library projects that require bundling.

**Comment by spatialillusions** [comment]
Well I merge the pull and we give it a try.

**Comment by spatialillusions** [comment]
Could you just explain or give a link to what the map file does? I'm a bit confused about that one.
And I saw a nifty sample of how rollup simply could grab the version number from the package.json, so that should be done in the next step.

**Comment by okwolf** [comment]
@spatialillusions [source maps](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map) allow CDN users (like from [unpkg.com](unpkg.com/milsymbol)) to debug the minified/uglified code with the original source showing in their debugger.
