### ISSUE TITLE
Remove Bower support

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#147]
Since there are quite few using bower now that NPM and Yarn sort of supports the same things as bower did, I suggest that the bower file will be removed to the next major.

**Comment by okwolf** [comment]
As one of the users who initially used Bower and then migrated away to npm, I agree. Don't spend effort maintaining something not bringing more delight to this world.

**Comment by spatialillusions** [comment]
There might be some polymer people using bower, but they have to let me know if they need it.
