### ISSUE TITLE
Wrong Mapping / Image for APP6 "Train Locomotive"

### ISSUE THREAD

**Issue by Sky-Flyer** [spatialillusions/milsymbol#167]
For the APP6 (alpha/bravo) Symbol "Equipment / Train Locomotive" with Symbol-Id-Code "SFG-EVST-------" Milsymbol draws the wrong Image.

It is obviously confused with the Milstd Symbol with the exact same code "Missile Support Vehicle Transloader". In Milstd b/c "Train Locomotive" got a new Symbol-ID-Code "SFG-EVT--------".

**In Unit Symbol Generator:**
![equipment-train-locomotive_spacial-illusions](https://user-images.githubusercontent.com/11425622/35433837-21ec00ee-0285-11e8-82ea-f7a50c091aef.PNG)

**APP6b Specification:**
![equipment-train-locomotive_app6b](https://user-images.githubusercontent.com/11425622/35433848-2bb760a0-0285-11e8-887e-5854c1a49e7e.PNG)

**Comment by spatialillusions** [comment]
Thank you very much for the heads up, I have fixed this in the master branch now.
