### ISSUE TITLE
No CI

### ISSUE THREAD

**Issue by ateshuseyin** [spatialillusions/milsymbol#180]
@spatialillusions Why don't you use continuous integration. https://travis-ci.org/ is also free for opensource projects. May I help you about it?

**Comment by spatialillusions** [comment]
Only reason is that I haven't had time. If you would like to help out it would be much appreciated.

**Comment by spatialillusions** [comment]
I have merged the pull so now it should work. Thank you very much for the help.

**Comment by okwolf** [comment]
Consider adding a build badge to the README similar to: [![Build Status](https://travis-ci.org/spatialillusions/milsymbol.svg?branch=master)](https://travis-ci.org/spatialillusions/milsymbol)

**Comment by spatialillusions** [comment]
I have added a badge to the readme now. Thank you for the heads up.
