### ISSUE TITLE
Make +- show ± for reinforced/reduced

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#184]
To make it look better, make an input of +- or -+ show ± instead.

**Comment by fabanc** [comment]
I like this idea, but wouldn't it make more sense to have the +- replaced by ± when setting the amplifier value, during the symbol creation time? I would be happy to look into that if you're short on time.

**Comment by spatialillusions** [comment]
A pull request for this would be welcomed.

**Comment by spatialillusions** [comment]
See #281 for a way to solve this.
