### ISSUE TITLE
Unable to change/fix the icon for sId["S-S-CLLLSU"]

### ISSUE THREAD

**Issue by YahavTheKing123** [spatialillusions/milsymbol#185]
Hey,

sId["S-S-CLLLSU"] is cosisnt of 2 icons:
1.       icn["SE.IC.LITTORAL COMBATANT SHIP"], -- creates the "LL" text
2.       icn["SE.M2.SURFACE WARFARE"] -- creates the "SUV" text

Currently the generated symbol is not according to 2525C standart.
I want to shift it a bit up but i counld find the right place in the code for doing so.

Of couse that if I am debugging and changging the drawInstruction to new x,y's values it works...

Thanks in advance :)

**Comment by spatialillusions** [comment]
Hi, 

The symbols in milsymbol are created according to how they are defined in 2525D/APP6C/APP6D, that makes them look not exactly as rendered in the 2525C/APP6B standard documents, but according to the people that created the standards this is still completely OK and there is actually translation tables between the different standards showing what symbols that are interchangeable. However, if you still want to change the symbols, do it like this: (Code is untested but should work.)

```javascript
ms.addIconParts(function(
  iconParts,
  metadata,
  colors,
  std2525,
  monoColor,
  alternateMedal
) {
  /*
    iconParts: Object - The existing object of icon parts
    metadata: Object - propterties object
    colors: Object - color object
    std2525: Boolean - Is it 2525 then true, otherwise false
    alternateMedal: Boolean - true/false for sea mine stuff
    */
  var affiliation = metadata.affiliation || "Friend";
  //If hostile and not monoColor, make it red, otherwise use the iconColor.
  var iconColor = colors.iconColor[affiliation];

  iconParts["SE.IC.LITTORAL COMBATANT SHIP"] = {
    type: "text",
    stroke: false,
    textanchor: "middle",
    x: 100,
    y: 115,
    fontsize: 42,
    text: "LL",
    fontfamily: "Arial",
    fontweight: "bold",
    fill: iconColor
  };
  iconParts["SE.M2.SURFACE WARFARE"] = {
    type: "text",
    stroke: false,
    textanchor: "middle",
    x: 100,
    y: 140,
    fontsize: 25,
    text: "SUW",
    fontfamily: "Arial",
    fontweight: "bold",
    fill: iconColor
  };
  /* 
    Since we are modifying directly to the existing object of icon parts, 
    we don't have to return anything.
    */
});
```
Then simply adjust the y values for the icons and they should move like you want. But keep in mind that if the same parts are use by other symbols, they will also be changed.

**Comment by YahavTheKing123** [comment]
Great. 
I appreciate your support.
