### ISSUE TITLE
Removing the squres frame from EMS.INCDNT.MRN.HJKG

### ISSUE THREAD

**Issue by YahavTheKing123** [spatialillusions/milsymbol#187]
When trying to generate the icon for EMS.INCDNT.MRN.HJKG (which SID's: OUOPHV----
*****, OFOPHV----*****, OHOPHV----*****, ONOPHV----*****), I saw that there is a 4 small squares frame that added to the corners of the icon. 
According to 2525C standrad doc the squres frame is missing and I would like to remove them.

What is the best way of doing that in your code ?(I saw the basegeometry.js file which adds it according to this.metadata.activity but I am not so sure how this param is being set and I also dont think that commenting the whole method is the correct solution).

Thanks for your time.

**Comment by spatialillusions** [comment]
If you comment out https://github.com/spatialillusions/milsymbol/blob/master/src/lettersidc/metadata.js#L49 the activity metadata property will never be set and you should not get the activity indicator on the frame.

**Comment by YahavTheKing123** [comment]
It worked. thank you.
