### ISSUE TITLE
Getting only purple background for the below SIDCs

### ISSUE THREAD

**Issue by YahavTheKing123** [spatialillusions/milsymbol#188]
Hey,

Can you please direct me to the place I can fix the SIDC's:
1. SUGPEVC---***** 
2. SFGPEVC---*****
3. SNGPEVC---*****
4. SHGPEVC---*****

For some reason when I am trying to generate the icon for them as SVG, i am getting a purple background and not according to the the F,U,N,E.. (in the standart I can see the background is yellow, blue, green and red like the other entities..)

Thanks

**Comment by spatialillusions** [comment]
This is by design, but check the documentation for `civilianColor`.

**Comment by YahavTheKing123** [comment]
Great.
Thanks for your assistance :)
