### ISSUE TITLE
2525C - Supporting 'Static operational condition modifiers for tactical symbols'

### ISSUE THREAD

**Issue by YahavTheKing123** [spatialillusions/milsymbol#189]
Hey,

Currenlty in milsymbol I see that the Static operational condition modifiers for tactical symbols are being generated with the buttom colored frame according to its condition (as in the attached pic this is the 'Alternate symbols for operational condition modifiers for tactical symbols' taken from the standart).

Is milsymbol supports the other way of generating the operational condition modifier (as in the picture of TABLE III-1. of marking an X or / on the symbol)?

If not, how can i achieve it? which files should I change inorder to get this ability.

Thanks for your support!

![image](https://user-images.githubusercontent.com/38849753/39674327-b7ee882a-5152-11e8-9cd1-8ba669f60536.png)
 
![image](https://user-images.githubusercontent.com/38849753/39674338-d9cba95a-5152-11e8-89e4-5a9c11ae6acf.png)

**Comment by spatialillusions** [comment]
By default milsymbol will use the simple status modifiers for unfilled symbols, and the colored status modifier for filled symbols, this can be changed by using the option `simpleStatusModifier` as listed in the documentation. It is also described in the rendering documents in the doc folder, that you can find a live preview of there. https://spatialillusions.com/milsymbol-dev/docs/milsymbol-2525c.html

**Comment by YahavTheKing123** [comment]
I appriciate your help! 
that's wokred for me.

Thank you
