### ISSUE TITLE
Zero direction does not show indicator

### ISSUE THREAD

**Issue by nstod** [spatialillusions/milsymbol#191]
Creating a symbol with a direction set to 0 will not show the heading indicator.  If I change the direction to 0.1 (or anything besides 0), it shows up.

**Comment by spatialillusions** [comment]
I have now verified that this is already fixed in the master branch.

**Comment by nstod** [comment]
Great, thanks!  Do you have any idea when this bug fix will make it's way to npm?

**Comment by spatialillusions** [comment]
I’m waiting for the official release of MIL-STD-2525D change 1, that is said to be released quite soon, but not quite sure when. And then I have to make sure that I have fixed everything the have changed between the draft I got and the final. 
However, you should be able to test it by running “npm -i milsymbol@next”.
