### ISSUE TITLE
What about an SIDC generator

### ISSUE THREAD

**Issue by orrgal1** [spatialillusions/milsymbol#192]
How is the user supposed to know what to enter in SIDC? There should be the option to pass an object with properties and  have translated to SIDC.

**Comment by spatialillusions** [comment]
Milsymbol is focused on rendering the symbols for when you know the sidc and already have some kind of UI for this. However, I have built such a UI that you can find here:
https://github.com/spatialillusions/milsymbol-generator
And if you want to create your own UI, all structure for the standards can be found here:
https://github.com/spatialillusions/milstd

**Comment by orrgal1** [comment]
ok thanks. i'll try to build something and maybe submit it as pull request into milsymbol. don't you think it would make a good feature? in my use case i don't know the sidc and must generate it on the fly. hence the above request.

**Comment by spatialillusions** [comment]
At the moment I’m not sure it would fit into milsymbol, but I’ll be happy to link to your code if you put it online in another repository.

**Comment by orrgal1** [comment]
alright. will update if i have anything.

**Comment by orrgal1** [comment]
hey there. would it be ok if i push it to milstd repo as a PR? or to the milsymbol-extensions repo?
