### ISSUE TITLE
Incorrect placement of direction mark for headquarters

### ISSUE THREAD

**Issue by tumick** [spatialillusions/milsymbol#193]
According to APP-6D standard, direction mark must appear from the bottom of headquarter's sign vertical line. 
See http://nso.nato.int/nso/zPublic/ap/PROM/APP-6%20EDD%20V1%20E.pdf
Page 1-12, figure 1-5, position 'Direction & Movement ' (page 36 in the file)
Instead, Milsymbol draws direction mark from center of the sign.

**Comment by tumick** [comment]
From standard:

![ms-plan](https://user-images.githubusercontent.com/128519/41457634-edb68e4a-708c-11e8-8837-9d698cd0b6bc.png)

Fact:

![ms-fact](https://user-images.githubusercontent.com/128519/41457651-fa0a4ee8-708c-11e8-8cb7-d327cc84550a.png)

**Comment by spatialillusions** [comment]
I have now added a fix for this and the direction arrow will move if it is a headquarters symbol.
![sfgpu-----a-](https://user-images.githubusercontent.com/8155542/41498440-35c0b698-716e-11e8-99c7-62ce8e6c146b.png)

**Comment by tumick** [comment]
Thanks a lot! 😎
