### ISSUE TITLE
Field artillery symbol text amplifier rendering error

### ISSUE THREAD

**Issue by kjellmf** [spatialillusions/milsymbol#196]
I noticed that the field artillery symbol is behaving strangely when adding text amplifiers:

![10031000001303000000](https://user-images.githubusercontent.com/29217/41581353-81c397c2-739e-11e8-94f6-b03c9b57fd1c.png)

In this case I've rendered the `10031000001303000000` symbol and set  `uniqueDesignation=2`.  

Tested using https://spatialillusions.com/unitgenerator/

**Comment by spatialillusions** [comment]
I have found where it happens and what is the cause of this bug. Now I just have to figure out how to solve it. 
When I add the label overrides for symbols there is no check to make sure they only are applied to tactical graphics, so I need to add that in some way.

**Comment by spatialillusions** [comment]
Might be in many places.... I realized that I don't make a check for the symbol set, so any code listed in https://github.com/spatialillusions/milsymbol/blob/e5770cc77dd5693e2ed4d487061c7c0504ac4fc9/src/numbersidc/labels/tactical-points.js that also is present in another symbol set will have the label overrides applied...

**Comment by spatialillusions** [comment]
Quick and dirty fix would be to add a check for the symbol set here:
https://github.com/spatialillusions/milsymbol/blob/master/src/symbolfunctions/textfields.js#L229
Better solution would be to have the symbol set check when the overrides are added.

**Comment by spatialillusions** [comment]
Think the solution was not so bad, so I did a version of the quick and dirty fix.

**Comment by spatialillusions** [comment]
ps. The unit generator on spatialillusions.com is also updated. ds.

**Comment by spatialillusions** [comment]
Just published RC4, so try get it again.
