### ISSUE TITLE
Add option to remove attribution - specifically for test runs

### ISSUE THREAD

**Issue by dougajmcdonald** [spatialillusions/milsymbol#199]
We would like the option to remove the attribution from our test runs. 

At the moment our tests output hundreds of `console.log` messages which can cause problems with CI which is not expecting any output.

E.g.

PASS  test/components/MapLayerDropdownItem.test.js
  ● Console

    console.info node_modules/milsymbol/dist/milsymbol.js:32
      milsymbol.js 1.3.3 - Copyright (c) 2017 Måns Beckman  http://www.spatialillusions.com

I understand you want to keep attribution in, but in testing it's actively a problem.

I can edit the build src, but that feels wrong and means repeating the process as and when we update the package.

**Comment by spatialillusions** [comment]
I added a check if the process object https://nodejs.org/api/process.html#process_process exists, and if it does I don't log the message. This should make it log in the webbrowser but not inte node.

**Comment by dougajmcdonald** [comment]
Ah brilliant, we are on an old version, I'll try to get this updated today, thanks for the response.
