### ISSUE TITLE
Add Fighter/Attacker for the Hornet.

### ISSUE THREAD

**Issue by rurounijones** [spatialillusions/milsymbol#200]
Add the ability to allow for Fighter / Attacker aircraft on the website. This will allow for the correct symbol for the F/A-18 Hornet.

I assume it requires a modification in https://github.com/spatialillusions/milsymbol/blob/d0a55eaa4732895b2998275ec16970962c3e0ece/src/lettersidc/sidc/air.js

I am not sure on the exact coding but I assume it would be something like the following.

```
sId["S-A-MFFA--"] = [icn["AR.I.FIGHTER ATTACK/STRIKE"]];
```

Plus whatever else needs to be done for icn to support it.

**Comment by spatialillusions** [comment]
As far as I can tell, I can't find that symbol code in either 2525B, 2525C or APP6B. If you can point me to a standard where it is available I can have a look at it. 
It is also possible to expand milsymbol with custom symbols outside the standard, and I can help out on a consultancy basis if you need this for a specific system.

**Comment by spatialillusions** [comment]
Ping @rurounijones. Is this a symbol code you have found in any of the standards? Or is it simply something you would like to add to a custom implementation of the library?
