### ISSUE TITLE
Remove the unit symbol flag pole

### ISSUE THREAD

**Issue by scottnc27603** [spatialillusions/milsymbol#213]
![flagpole](https://user-images.githubusercontent.com/1278173/48522373-65ea2a80-e846-11e8-8208-ea63ae60c014.png)

I had reviewed some information about the 'flag pole'/group rendering.  This one feature is going to keep us from using milsymbol.  How do disable this feature?

**Comment by scottnc27603** [comment]
found it!
ms.setHqStafLength( 0 )

**Comment by spatialillusions** [comment]
Added in latest commit the possibility to remove the staff, set ms.setHqStaffLength(0) or use the option hqStaffLength:-1 on individual symbols. Also make sure to use octagon center for your insertion point, because the other insertion point will still use the end of the pole.
