### ISSUE TITLE
APP6D. Land equipment. incorrect icons

### ISSUE THREAD

**Issue by zizizuq** [spatialillusions/milsymbol#214]
Could you please fix icons for Land equipment for APP6D
Actual result:

![image](https://user-images.githubusercontent.com/45353847/49006179-276f3c80-f171-11e8-9d4d-95bec34ca177.png)
![image](https://user-images.githubusercontent.com/45353847/49006550-08bd7580-f172-11e8-80c0-09aca67be533.png)

Expected:

![image](https://user-images.githubusercontent.com/45353847/49006215-3eae2a00-f171-11e8-8aff-15053641c13d.png)
![image](https://user-images.githubusercontent.com/45353847/49006804-926d4300-f172-11e8-9f2d-77f023d3a80c.png)

**Comment by spatialillusions** [comment]
Fixed in master branch, will update the unit generator in the next update.

**Comment by zizizuq** [comment]
thanks
