### ISSUE TITLE
Does milSymbol support the offest indicator 'S'?

### ISSUE THREAD

**Issue by YahavTheKing123** [spatialillusions/milsymbol#217]
Hello Mans,

I am trying to render with milSymbol the 'offset Location indicator' but:

1. I am not sure its an sidc modifer, from the 2525 docs I can see that only the HQ indicator is control by the sidc.
2. There is a way to create this modifier with your package? In modifier.js file, only the hq modifier is being rendered..

Thanks :)

**Comment by spatialillusions** [comment]
Nope, this will have do be done in the mapping library you use for your symbols. Milsymbol can do the speed leader indicator, but not the offset.
