### ISSUE TITLE
What is `size` option?

### ISSUE THREAD

**Issue by stalniy** [spatialillusions/milsymbol#218]
It's hard to interpret `size` option. Is it font size, width, height or something else?

**Comment by spatialillusions** [comment]
From the documentation:
The L value for your symbol, where the L value is the width of the icon octagon.

IIRC size:100 will make the octagon 100px. And the octagon referred to is the octagon where all parts of the icon is placed within and that is completely within the symbol frame.

**Comment by stalniy** [comment]
Thanks! That’s helpful
