### ISSUE TITLE
ES6 errors

### ISSUE THREAD

**Issue by scottnc27603** [spatialillusions/milsymbol#223]
I ran into some issues with adding milsymbol to a React application.  Apparently all of the import calls need to be at the start of the file?  Anyway, I can submit a PR, but it appears that I'm unable to create a branch?

**Comment by spatialillusions** [comment]
There shouldn't be anything that prevents you from making a fork... The reason could be that you already have an old fork of milsymbol as one of your repositories. Could you try to remove the old fork and fork it again?

**Comment by scottnc27603** [comment]
10-4 Mans, thanks for all of your hard work!  I'm trying to figure out how
to modify everything for the latest eslint without going through all of the
code

**Comment by spatialillusions** [comment]
Could it be that you cant fork the library because you already have an old fork?

**Comment by scottnc27603** [comment]
I did see that there was a es6 branch after sending the message.  Our funds
for the project have been on hold for a while, so I haven't had a need to
deal with the issue.  I may get back to this issue early next year.

Scott
