### ISSUE TITLE
2525C: Mobility Indicator wrong for Barge and Amphibious

### ISSUE THREAD

**Issue by dehmer** [spatialillusions/milsymbol#224]
From my understanding of MIL-STD-2525C (Appendix A, TABLE A-II) the SIDC values for equipment mobility indicator should be the following:

* Barge: MX (not MY)
* Amphibious: MY (not MZ)

Can you confirm?

**Comment by spatialillusions** [comment]
This could be correct, I'll look into it when I get time, unfortunately I have quite a lot to do with other things at the moment.
