### ISSUE TITLE
symbol infoField flag not honored by all symbols

### ISSUE THREAD

**Issue by dehmer** [spatialillusions/milsymbol#229]
Setting `infoFields` to false does not remove labels from all symbols.
While it works on units, equipments and such, labels on (general) points (e.g. 'START POINT') stay visible.

I don't if it is the intended behavior, but it would be nice if `infoField` would have an effect on all symbols.

**Comment by spatialillusions** [comment]
IIRC that text is part of the symbol "icon" and because of this the text is not removed. infoField just removes text thats that has been set by the user. I'll consider for the future if I should change this.
