### ISSUE TITLE
Some APP-6D incorrectness

### ISSUE THREAD

**Issue by tumick** [spatialillusions/milsymbol#236]
There are 2 issues (actually 8: 2 subsets of 4) found in APP-6D realization.

Official specification got from here:
https://nso.nato.int/nso/nsdd/apdetails.html?APNo=1912

Illustration of incorrectness in pics:
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()
![Uploading 4.png…]()

**Comment by tumick** [comment]
Do not know why, but I can not upload image attachments to this issue.

It's about following codes:

(pages 3-92, 3-96, 3-97 in the specification)

HOWITZER
Type: Entity Type
Entity: WEAPON/WEAPON
SYSTEM
Symbol Set Code: 15
Code: 110900
Icon Type: Full Octagon


HOWITZER – LIGHT
Type: Entity Subtype
Entity/Entity Type:
WEAPON/WEAPON SYSTEM/
HOWITZER
Symbol Set Code: 15
Code: 110901
Icon Type: Full Octagon


HOWITZER – MEDIUM
Type: Entity Subtype
Entity/Entity Type:
WEAPON/WEAPON SYSTEM/
HOWITZER
Symbol Set Code: 15
Code: 110902
Icon Type: Full Octagon


HOWITZER – HEAVY
Type: Entity Subtype
Entity/Entity Type:
WEAPON/WEAPON SYSTEM/
HOWITZER
Symbol Set Code: 15
Code: 110903
Icon Type: Full Octagon


SURFACE-TO-SURFACE
MISSILE LAUNCHER
Type: Entity Type
Entity/Entity Type:
WEAPON/WEAPON SYSTEM
Symbol Set Code: 15
Code: 111300
Icon Type: Full Octagon

SURFACE-TO-SURFACE
MISSILE LAUNCHER – LIGHT
Type: Entity Subtype
Entity/Entity Type:
WEAPON/WEAPON
SYSTEM/SURFACE TO
SURFACE MISSILE LAUNCHER
Symbol Set Code: 15
Code: 111301
Icon Type: Full Octagon

SURFACE-TO-SURFACE
MISSILE LAUNCHER – MEDIUM
Type: Entity Subtype
Entity/Entity Type:
WEAPON/WEAPON SYSTEM/
SURFACE TO SURFACE
MISSILE LAUNCHER
Symbol Set Code: 15
Code: 111302
Icon Type: Full Octagon
N/A
SURFACE-TO-SURFACE
MISSILE LAUNCHER – HEAVY
Type: Entity Subtype
Entity/Entity Type:
WEAPON/WEAPON SYSTEM/
SURFACE TO SURFACE
MISSILE LAUNCHER
Symbol Set Code: 15
Code: 111303
Icon Type: Full Octagon

**Comment by av-dev** [comment]
![1](https://user-images.githubusercontent.com/21226754/67553849-c6e8d680-f716-11e9-92c2-1da7c1edbccb.png)
![2](https://user-images.githubusercontent.com/21226754/67553850-c6e8d680-f716-11e9-81ed-2bae47572f06.png)
![3](https://user-images.githubusercontent.com/21226754/67553851-c6e8d680-f716-11e9-92b4-d456207319e7.png)
![4](https://user-images.githubusercontent.com/21226754/67553852-c7816d00-f716-11e9-847d-f62d5837bfcc.png)

**Comment by spatialillusions** [comment]
I'll look into this.

**Comment by tumick** [comment]
> I'll look into this.

Thanks a lot!

**Comment by multum** [comment]
@spatialillusions Hi! I would like to contribute and take this
