### ISSUE TITLE
with nodejs in desconected environment

### ISSUE THREAD

**Issue by vmbajop** [spatialillusions/milsymbol#239]
Hi and thanks for the tool, is great.
Is it possible to install milsymbol in nodejs in an desconected from internet environment?
I have been several test with milsymbol library in wwwroot (sometimes with npm -g for global install), in nodejs folder, in project (app) folder... I have assumed that it must create a folder called .dist/milsymbol.
Nevertheless I don't get anyhing and npm only write some errors and warnings.

**Comment by BaaltRodrigo** [comment]
You can install **milsymbol** normally with npm (or cloning the repo and add it to your project) and turn off the wifi and it will work normally. I just test it and works fine for me.
