### ISSUE TITLE
Dictionary for a unit generator

### ISSUE THREAD

**Issue by amarant** [spatialillusions/milsymbol#25]
Following the issue #21 it would be nice to be able to have a dictionary of possible choice to make a custom unit generator like the one included in the project.

**Comment by spatialillusions** [comment]
I'm wokring on creating a javascript tree structure for the standards that will be used in a new version of the unit generator and other examples.

**Comment by spatialillusions** [comment]
@amarant Would you be interested in trying out my concept for a dictionary/validation function for MIL-STD-2525C appendix A? It would be quite easy to add more appendixes or change it to APP6b, but I want to know that it looks like a good concept.

**Comment by amarant** [comment]
yes I would be happy to test it in a product that I develop for a client, we currently have a validation dictionary that is not really accurate.

**Comment by spatialillusions** [comment]
@amarant I made a initial pull to extras/test.html, this shows the data structure that I'm thinking would be the result. There are still some minor things to do and it will have to be wrapped in a javascript function. My plan is to make similar data structures for App6 and 2525D as well and then migrate the unit generator example to use them.

**Comment by amarant** [comment]
Thanks, I'm gonna have a look at it.

**Comment by spatialillusions** [comment]
The source code for the unit generator is now provided under dev, there won't be any more general code for the moment. Please provide a pull request if you have some better code.
