### ISSUE TITLE
Cannot change portion of color on milsymbol

### ISSUE THREAD

**Issue by krotte1** [spatialillusions/milsymbol#251]
I have a symbolCode of "SFGPUUMSE--F***" that I am loading on my map that has a darker background that causes a portion of the military symbol to be unreadable. I tried a number of different options and was not able to change the color of the two verticle lines that lie outside and above the icon. It does not respond to infoColor or infoBackgroundColor.

The symbol looks like:
![image](https://user-images.githubusercontent.com/46959599/88320573-ff840380-ccda-11ea-9e04-243452bed59e.png)

The symbol in the map with unrecognizable verticle lines at the top
![image](https://user-images.githubusercontent.com/46959599/88320673-2d694800-ccdb-11ea-9327-9c869e4c1335.png)

**Comment by vmbajop** [comment]
Hi.
Try with options:
outlineColor and outlineWidth, wich you can see in the help: [https://www.spatialillusions.com/milsymbol/documentation.html](url)

**Comment by spatialillusions** [comment]
Like vmbajop says, use outlines for making the symbols easier to read on a map.
