### ISSUE TITLE
Is this project still maintained or actively developed?

### ISSUE THREAD

**Issue by rob-64** [spatialillusions/milsymbol#253]
@spatialillusions 

Sorry for making an issue, but just wondering the state of the project?

**Comment by spatialillusions** [comment]
I have been away doing other stuff for quite a while, and didn't really have a computer where I could do any development, but now I'm back. Focus will be on fixing bugs and making sure that everything follows the standards. 

I do have some plans for how the library could have a major update in the future, but not quite sure how big the benefit would be for most people.
