### ISSUE TITLE
milsymbol not working properly on terrain data of cesiumjs

### ISSUE THREAD

**Issue by adeelahmed1981** [spatialillusions/milsymbol#259]
hi,
I am working on cesium when I add a unit symbol on cesium globe which have terrain data .The placed symbol on terrain data is changing it position when we rotate the view .Is there any solution to counter this problem?
thanks

**Comment by spatialillusions** [comment]
This sounds like a cesium bug and not a milsymbol bug. If you think it is a milsymbol bug, please provide a code example showing another image icon that works and describe what you think should be changed in milsymbol.
