### ISSUE TITLE
Anchor Information

### ISSUE THREAD

**Issue by cursorcl** [spatialillusions/milsymbol#260]
When I like to draw symbols asCanvas in Cesium and apply getAnchor() -x and -y offset the icon is showed far of the setting position.

It always happend when I enable infoFields how in the image.
![problem](https://user-images.githubusercontent.com/5521470/117169852-7b959680-ad97-11eb-8e7c-8a45829dc354.png)

How I know the correct offset to apply?

**Comment by spatialillusions** [comment]
Sort of like this should work. 

https://cesium.com/blog/2016/07/20/cesium-and-milsymbol/

**Comment by cursorcl** [comment]
It is precisely from this page that I have taken the example.

When placing the texts, the size of the resulting canvas grows and the offset is apparently not correct.

**Comment by spatialillusions** [comment]
Just used the octagon offset in another program, if it doesn't work, it is a bug in Cesium and not in milsymbol. If you still think it is a milsymbol bug, please provide a code example.
