### ISSUE TITLE
 milsymbol - Install failure on Linux (offline)

### ISSUE THREAD

**Issue by jabba277** [spatialillusions/milsymbol#262]
I'm trying to install milsymbol on Linux PC with no internet - via .tar.gz file on a USB.
I installed NodeJ (v16.13 / npm 8.1).
1) Extracted the milsymbol-2.0.0.tar.gz file
2) cd to extracted folder
3) npm install
    Got a ton of warnings w.r.t. unable to connect to npm.registry because an older npm was used - but I read that one can just ignore the warnings...
    Then it stopped on an error - could not find eslint-plugin.

Is there a way to download milsymbol with all its dependancies in a single archive? Or do I have to download every dependency in the repo's dependencies section?

[milsymbol_install.log](https://github.com/spatialillusions/milsymbol/files/7610457/milsymbol_install.log)

Appreciate your help on this.

Regards
[Lum](url)

**Comment by spatialillusions** [comment]
Here you go, built and ready to use. 
https://spatialillusions.com/milsymbol/dist/milsymbol.js

If you want the full unit generator, in an offline system, it can be found here:
http://spatialillusions.com/unitgenerator/unitgenerator.zip

**Comment by jabba277** [comment]
Thanks, Mans!    milsymbol.js worked wonderfully...
All I wanted was to programmatically generate MIL-2525 symbols  as SVG files.

**Comment by jabba277** [comment]
Hi Måns,

 

I was able to get a javascript working with milsymbol.js to generate 2525 .svg files using nodeJ interpreter.

 

Whilst testing, I noticed that the positioning of the symbol centre for “SHGPUCDG—A-“ was slightly off vertically.

 

I have attached pics of the source system to be compared with the target system – the source system sends “SHGPUCDG—A-***” and a position to the target system to display.

The target system displays “SHGPUCDG---***”  correctly.

 

I’ve attached the associated files.

 

Appreciate your help on this.

 

Regards

Lum

**Comment by spatialillusions** [comment]
Your pictures didn't get here. And you need to provide more information about how you are placing your symbol. 
Have you looked at the samples and the different ways milsymbol can provide you with information about the center of the symbol? 

/Måns

**Comment by jabba277** [comment]
I've attached the 2 pics (this time .jpg).We're using geotools PointSymbolizer to display the .svg.Looking at the pictures now, it looks like geotools is just taking the height of the image  and halving - which makes sense logically, but not what we would like to see.
Could you send me a link to the samples mentioned in your emails?It would be great if there logic to provide X,Y displacement to the centre of the tactical symbol (minus modifiers).
Thank you for your quick reply.
RegardsLum

Lum Hwang email(personal): ***@***.***

**Comment by spatialillusions** [comment]
You can find all sampels here:

https://spatialillusions.com/milsymbol/index.html

And of you check under style options in the documentation, you can find the ”square” option that will solve your problems. Now you own me a 🍺. 😆

/Måns

**Comment by jabba277** [comment]
With "square" true, it seems to be using bottom left as the anchor point...Well, does it look like I'll need to retrieve the getAnchor() value and pass the X,Y displacement to geotools? (and with square false)
Right now, you're up to a non-alcoholic beer! ;-)

Lum Hwang email(personal): ***@***.*** 

    On Thursday, December 2, 2021, 09:49:03 a.m. EST, Måns Beckman ***@***.***> wrote:  
 
 

You can find all sampels here:

https://spatialillusions.com/milsymbol/index.html

And of you check under style options in the documentation, you can find the ”square” option that will solve your problems. Now you own me a 🍺. 😆

/Måns

> On 2 Dec 2021, at 15:12, jabba277 ***@***.***> wrote:
> 
> ﻿
> I've attached the 2 pics (this time .jpg).We're using geotools PointSymbolizer to display the .svg.Looking at the pictures now, it looks like geotools is just taking the height of the image and halving - which makes sense logically, but not what we would like to see.
> Could you send me a link to the samples mentioned in your emails?It would be great if there logic to provide X,Y displacement to the centre of the tactical symbol (minus modifiers).
> Thank you for your quick reply.
> RegardsLum
> 
> Lum Hwang email(personal): ***@***.*** 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by spatialillusions** [comment]
That’s strange, with square:true you should get a square symbol where the insertion point is in the center. Must be your frontend that does something special with square symbols.
