### ISSUE TITLE
Unable to apply color to mine symbol background

### ISSUE THREAD

**Issue by 32dohs** [spatialillusions/milsymbol#263]
Hello all,

I am trying to create symbols that have a black frame and a white background.

I was able to achieve that for the most part by doing this:

**var sym = new ms.Symbol("SFUPWM------***", { size: 20, colorMode: "White" });

	sym.setOptions({
		frameColor: {
			Civilian: "black",
			Friend: "black",
			Hostile: "black",
			Neutral: "black",
			Unknown: "black",
		}
	});**

However, mine icons seem to be the exception.  That background is always transparent, and I have been unable to find a way to get them styled the way I want.  I have a picture to illustrate.

![MinesTransBkgrnd](https://user-images.githubusercontent.com/80270964/145036564-ffc519cb-09d3-40e7-bd8e-3019b69ed012.PNG)

The version I am using is 2.0.0.

Is there any way to achieve what I need?

Thank you in advance for any help you can provide.

- Eric

**Comment by spatialillusions** [comment]
You can sort of do this... If you use number based SIDC from MIL-STD-2525D or APP6 D, and set alternateMedal:true, at the moment there isn't another way that I can think about.

**Comment by 32dohs** [comment]
Thank you for the assistance.  I reworked my code based on your suggestion and I was able to generate the icons with the styles they need.
Many thanks!
- Eric
