### ISSUE TITLE
monoColor

### ISSUE THREAD

**Issue by muby** [spatialillusions/milsymbol#265]
Hello, 

I would to know there is a simple way to get MonoColor that can take a string like today or a ColorMode ?

Thanks a lot

**Comment by spatialillusions** [comment]
Hi,

You can override the built in color mode FrameColor. 

https://github.com/spatialillusions/milsymbol/tree/master/docs#msgetcolormodemode

That should solve your problem. 

/Måns

**Comment by muby** [comment]
I think I was not clear or I don't understand you answer :)

What I want to do is to be able to assign ColorMode to monoColor. 

For example : 
**Working :** 
```
new ms.Symbol("SFGPEVAC--**--*", {
      }, {standard:"APP6",monoColor:"red",size:200}).asSVG()
```
or

**Not Working**
```
new ms.Symbol("SFGPEVAC--**--*", {
      }, {standard:"APP6",monoColor:ms.ColorMode("purple", "blue", "red", "green", "yellow"),size:200}).asSVG()
```

```
new ms.Symbol("SFGPEVAC--**--*", {
      }, {standard:"APP6",monoColor:ms.getColorMode("Light"),size:200}).asSVG()
```
