### ISSUE TITLE
iconColor has no effect for SIDC EO* and WO* (NodeRED World Map)

### ISSUE THREAD

**Issue by sgofferj** [spatialillusions/milsymbol#268]
I'm not sure if that's a bug or if I'm misunderstanding the documentation. I'm plotting GDACS reports to a NodeRED World Map with the SIDCS "EOIPCH------", "EONPBB------", "EONPAC------", "WOSPWSTSS---" or "EONP--------". This is my object:
```
    msg.payload = {
      name: callsign,
      tooltip: tooltip,
      lat: event["point"][0]["$"]["lat"],
      lon: event["point"][0]["$"]["lon"],
      bearing: bearing,
      SIDC: SIDC,
      ttl: ttl,
      weblink: weblink,
      layer: layer,
      options: { iconColor:ic }
    };
```
For iconColor I use "red","orange","green" and false. The icons, however, are still being plotted in black. If I change iconColor to infoColor, the text is displayed in the appropriate color which makes me think that my object is correct and there might be an issue with milsymbol.

Versions:
NodeRED: 2.2.2
World Map 2.28.0

**Comment by spatialillusions** [comment]
If you read the documentation the iconColor should be set to a ColorMode, not a string.
