### ISSUE TITLE
Searchable milsymbols

### ISSUE THREAD

**Issue by sjlynch** [spatialillusions/milsymbol#270]
Hi!

Is there a way to search for symbols using human readable text vs using SIDC? For example, if a user types in "fishing", "leisure" or "missile" then I want all of the icons related to the search term to appear. I know how to implement the actual search, that's easy, the problem I'm facing is that I can't find a way to map human readable text to the SIDC for each symbol.

I sort of see how the document https://spatialillusions.com/milsymbol/docs/milsymbol-2525d.html is created in source, but I don't think those labels are exposed in the milsymbol library itself, are they? Short of manually building and/or copy/pasting a SIDC<->Human-readable-text, is there any easier way to do this that I'm not seeing?

Thanks!

**Comment by kjellmf** [comment]
Måns has published symbology data (with labels and sidcs) in separate repositories:
- https://github.com/spatialillusions/stanag-app6
- https://github.com/spatialillusions/mil-std-2525

I have used this data to search for symbols in a couple of projects. You basically end up with a large list of objects you can search through. If you are familiar with Vue.js you can find a few examples below: 

Building a searchable list:
https://github.com/kjellmf/orbat-mapper/blob/665b796e60969d4c6a2c1938f6605d29857922bb/src/composables/symbolData.ts#L27

Doing the actual search: https://github.com/kjellmf/orbat-mapper/blob/665b796e60969d4c6a2c1938f6605d29857922bb/src/components/SymbolPickerModal.vue#L162

Constructing the final SIDC: https://github.com/kjellmf/orbat-mapper/blob/665b796e60969d4c6a2c1938f6605d29857922bb/src/components/SymbolPickerModal.vue#L172

**Comment by sjlynch** [comment]
Thank you!! This is exactly what I was hoping for!
