### ISSUE TITLE
render tactical symbols

### ISSUE THREAD

**Issue by NoviceInWeb** [spatialillusions/milsymbol#272]
hello, @spatialillusions and @kjellmf 

I have a question.
I'm using a normal 2D canvas(no 3D map, no cesium, no openLayers)
So I used the svg type.
However, some returned images were marked with a 'question mark' as shown below.
The function I used seems to be 'multipoint' returns a 'question mark'.
In short, can you tell me the function that I can draw for 'multipoint'? Or is there an example?

[The result I wanted]
![Arrow](https://user-images.githubusercontent.com/82218832/177262674-93710286-4a4e-4def-8456-e58097dd442e.PNG)
![circle](https://user-images.githubusercontent.com/82218832/177262693-7c5feeec-1728-49f3-89ab-ac2b8abd98bc.PNG)

[Reality]
![image](https://user-images.githubusercontent.com/82218832/177260798-80618bd4-a1c0-442a-b68f-0b51471cd3ab.png)

[My Render Code]
```
let myTactical= ['GFT*I-----****X','GFT*N-----****X','GFT*D-----****X','G*T*F-----****X','G*T*AS----****X','G*T*E-----****X','G*T*O-----****X','G*T*Q-----****X', 'G*T*S-----****X','G*G*OAF---****X','G*T*B-----****X','G*T*H-----****X','G*T*Y-----****X','G*T*C-----****X','G*T*X-----****X','G*T*J-----****X','G*T*UC----****X']; 

--> (each symbolElement)

let renderedContent = new ms.Symbol(myTactical[symbolElement], { size: size, uniqueDesignation: element, additionalInformation: element, infoFields: "textInfo" }).asSVG();

ctx.beginPath();
ctx.drawImage(myTactical[symbolElement], x1, y1, x2 - x1, y2 - y1);
ctx.stroke();
```

Thank you...😒

**Comment by spatialillusions** [comment]
Hi, 

Milsymbol only supports point symbols and not any multipoint symbols. You can find all supported symbols in the documentation. 

/Måns

**Comment by ThomasHalwax** [comment]
@NoviceInWeb Drawing tactical graphics is not trivial. Take a look at our open source C2IS [ODIN](https://github.com/syncpoint/ODIN).

**Comment by NoviceInWeb** [comment]
thank you!

**Comment by NoviceInWeb** [comment]
> @NoviceInWeb Drawing tactical graphics is not trivial. Take a look at our open source C2IS [ODIN](https://github.com/syncpoint/ODIN).

thank you!

**Comment by jrblanno** [comment]
Hi! I love your project! you are a genius! any plans to support multipoint?
