### ISSUE TITLE
what is rbb error?

### ISSUE THREAD

**Issue by NoviceInWeb** [spatialillusions/milsymbol#273]
hi, @spatialillusions 

I try to draw multipoint figure at my canvas.
figure was painted. but It log occurred.

Can you tell me why? what is rbb?
It occurs when the mouse is dragged.
thank you.

![error](https://user-images.githubusercontent.com/82218832/180973899-e0c20dc2-f4df-47e2-83e0-e0a58624009c.png)

**Comment by spatialillusions** [comment]
Multipoint figures? Milsymbol only support single point symbols. 

/Måns
