### ISSUE TITLE
Publishing latestest version to npm

### ISSUE THREAD

**Issue by yevhenii-username** [spatialillusions/milsymbol#274]
Hey, Måns
Can I ask you to publish the latest version to npm 

Currently npm version - 2.0.0 - from [on 7 Feb 2019](https://github.com/spatialillusions/milsymbol/commit/fb5f6840a8fa4f342aaca249c6169761d252d723)

Currently master version from [12 Dec 2019](https://github.com/spatialillusions/milsymbol/commit/1c17e57282f505fb9ebcd42e04ef2ab1e1b102e6)

Thanks!

**Comment by spatialillusions** [comment]
Done https://www.npmjs.com/package/milsymbol
