### ISSUE TITLE
Center symbol with modifier fields while maintaining consistent size

### ISSUE THREAD

**Issue by slutske22** [spatialillusions/milsymbol#279]
Hi Mans, 

Thank you for this wonderful library.  I am struggling to understand the documentation, and some of the methods surrounding getting consistent symbol sizes, while keeping the main symbol centered.  It seems that when adding modifier fields, the central symbol is pushed over to the side:

![Screen Shot 2023-02-24 at 2 33 00 PM](https://user-images.githubusercontent.com/52637023/221325340-30abf157-ff36-4704-9362-909ead6edc46.png)

One thing that does indeed solve this is using the `square: true` property in the style object:

![Screen Shot 2023-02-24 at 2 33 35 PM](https://user-images.githubusercontent.com/52637023/221325382-10f724f4-6fb4-4457-8493-84f7b3412c1e.png)

However, if 2 symbols are side by side, and the only difference is the modifier field, using this property results in inconsistent sizing in say, a leaflet map:

![Screen Shot 2023-02-24 at 2 34 09 PM](https://user-images.githubusercontent.com/52637023/221325425-eecfb506-087a-476e-b8e3-331503907b88.png)

I have been digging through the docs, and the methods `getAnchor` and `getOctagonalAnchor` seem like they'd return some information I can use to manually offset the center of the image without needing to use `square: true`, but I really am not understanding what these values return.

[Here is a codesandbox](https://codesandbox.io/s/milsymbol-centering-ou5e05?file=/src/index.ts:1750-2101) demonstrating these issues in leaflet.  There are a few variations there.

How can one use the `getAnchor` or `getOctagonalAnchor` methods to get an actual pixel offset to center the symbol in the center of a container which wraps the svg/img/canvas element?

**Comment by spatialillusions** [comment]
Hi, 

If you check under examples there are two examples, one for divIcons in Leaflet and one for imageIcons.

In your case, what you want to do is something like this:

```
const marker2 = L.marker(point2, {
  icon: L.divIcon({
    html: symbol2.asSVG(),
    iconSize: [symbol2.getSize().width, symbol2.getSize().height],
    iconAnchor: [symbol2.getOctagonAnchor().x, symbol2.getOctagonAnchor().y],
    className: "mil-marker"
  })
}).addTo(map);
```

Thanks for making a codesandbox!
