### ISSUE TITLE
toDataUrl is not correctly creating images

### ISSUE THREAD

**Issue by shadowedice** [spatialillusions/milsymbol#280]
In [commit ebd26b2](https://github.com/spatialillusions/milsymbol/commit/ebd26b27530bb836a9bb6a8cd953004982618d9d), unescape was removed because it is deprecated. This now causes the SVG images to have an encoded URI which does not produce an image that can be used. I think there are two potential fixes:

1. Remove the encodeURIComponent. This would revert it to how it was previously.
2. Replace the unescape with decodeURIComponent.

**Comment by spatialillusions** [comment]
Thanks for finding this. 
I found a fix online that I tested and it looks like it solves the problem. At least I got it working in the application I'm working on at the moment.

**Comment by shadowedice** [comment]
Thanks for the quick fix. Looks to be working on my end as well.
