### ISSUE TITLE
High Contrast Background 

### ISSUE THREAD

**Issue by naaly17** [spatialillusions/milsymbol#283]
In situations where dark background is set, the Echelon symbol can be hard to view/identify, can an option be added to apply a high contrast background for this case?

**Comment by honymissy1** [comment]
Yes an option can be set and I can code that for you if I'm permitted

**Comment by naaly17** [comment]
Thank you! @honymissy1

**Comment by spatialillusions** [comment]
Hi, just set the option outlineColor to the color you want, and outlineWidth to the width of the outline. See the documentation.

**Comment by naaly17** [comment]
That should work, thank you!

**Comment by honymissy1** [comment]
Wish I could work with you again
