### ISSUE TITLE
Wrong symbols rendered for 3 codes

### ISSUE THREAD

**Issue by AndreZeiler** [spatialillusions/milsymbol#286]
I have found an issue that causes a few codes to be renderered in a wrong way.
I have a Land Unit where I set the Sector 1 Modifier.
The last correct modifier is Route, Reconnaissance, and Clearance (Symbol Set Code: 10, Code: 79)

The following modifers are rendered wrong.
I can confirm this here (https://www.spatialillusions.com/milsymbol/docs/milsymbol-APP6d.html#heading-15) as well as in my application.

I expect the shortcut:
 - CPN for COMMAND POST NODE not TR  (Symbol Set Code: 10, Code: 80)
 - JNN for Joint Network Node not CPN       (Symbol Set Code: 10, Code: 81)
 - RTNS for Retransmission Site not JNN       (Symbol Set Code: 10, Code: 81)

Bets regards

André Zeiler

**Comment by spatialillusions** [comment]
This should now be fixed in the current codebase and will be included in the upcoming 3.0 release.
