### ISSUE TITLE
In need of caching mechanism 

### ISSUE THREAD

**Issue by onderaltintas** [spatialillusions/milsymbol#296]
When the object is moving draw call happens with 33ms periods. Only direction arrow changes. That causes flickering on map. Is there a possibility of caching base icon (without modifiers) and apply changes for every draw call?

If you can point out the related location on code base, I believe I can also apply that kind of caching mechanism as well. 

Thank you,

**Comment by hasan4938** [comment]
Waht are you Doing?

**Comment by spatialillusions** [comment]
There is a caching mechanism, but not for this kind of use. I would suggest that you request the symbol without the direction arrow, and then draw it on your map manually behind the symbol as another map symbol.
