### ISSUE TITLE
Can i set stroke to icon besides outline?

### ISSUE THREAD

**Issue by serdaryesilmurat** [spatialillusions/milsymbol#298]
I create a symbol as shown below. This code creates a symbol with icon only and a white outline around it. But for "unknown/pending" affiliations, white outline is not visible. I want to set a black stroke around the icon (like in ) to make the outline and icon itself distinguishable.

(White outline has a meaning. So, it cant change it to another color.)

```
new ms.Symbol("30010100001101000000" , {
                frame:  false,
                fill: false,
                icon: true,
                iconColor: ms.getColorMode("Light"),
                outlineWidth:  5,
                outlineColor:  "white",
            })
```

Basically, i want the outline of the first image around the icon in the second image (which is created with 1px black outline) to obtain the third image.

![image](https://github.com/user-attachments/assets/94f0b16a-073a-483e-b0dd-6af9979c89eb)

As a solution, I can draw two symbols on top of each other on a single canvas, but I would appreciate it if there is a better solution.

**Comment by spatialillusions** [comment]
Hi, 

Sorry this is not possible with the built in functions. What you could do, is creating your own extension that is called after you have the icon geometry and then calls code similar to this 

```js

    if (this.style.outlineWidth > 0)
      drawArray1.push(
        ms.outline(
          drawArray2,
          this.style.outlineWidth,
          this.style.strokeWidth,
          typeof this.style.outlineColor === "object"
            ? this.style.outlineColor[this.metadata.affiliation]
            : this.style.outlineColor
        )
      );

```

That is how the outline is added in all other parts of milsymbol.
