### ISSUE TITLE
Stack and Country icon modifications not showing.

### ISSUE THREAD

**Issue by Pip1987** [spatialillusions/milsymbol#304]
Not sure if I'm setting these right, but when I set stack to 2 and country to usa with the following initializer
``$("#symbol").html(new ms.Symbol("30001000000000000000", { stack:2, country: 'USA'}).asSVG());``

For the flag I have also tried to match the generated json file with country_flag instead of country but get the same thing. All other symbols appear to be working just fine.

I expect to get:
![image](https://github.com/user-attachments/assets/b79facee-5554-4e70-aaef-b4aea6609e13)
but I get the following instead:
![image](https://github.com/user-attachments/assets/2bf010ee-51bb-409e-8459-bffec207ea4a)

**Comment by spatialillusions** [comment]
Stack and country flag are milsymbol extensions that aren't part of the milsymbol library. 
They are in a way breaking how symbols should be visualized according to MIL-STD-2525, so I kept them outside. 

If you are interested in the functionality, please send me an email if you would be interested in paying for that code.
