### ISSUE TITLE
Tactical graphics

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#32]
milsymbol dosen't draw tactical graphics and except a few point symbols that are referenced in other appendixes. If I would implement tactical graphics it would probably be done in another library, so that it will be easy to choose if you want to import it or not. 

I have for quite some time been collecting ideas for how I would be able to create tactical graphics, and unfortunately my time might be too limited to implement the whole tactical graphics appendix, but I have some ideas that I might try out.

My idea is to start out with some, maybe five or ten, different graphics and see how it works out. If anyone has any input, wishes, questions, please post them here and I'll try to answer. (And if you need this done faster, you can always take me in as a consultant.)

**Comment by kjellmf** [comment]
If you want inspiration, I know of two open source libraries that can draw control measures:

* [milsymb-js](https://github.com/missioncommand/mil-sym-js) / [milsymb-java](https://github.com/missioncommand/mil-sym-java)
* [MilSymb](http://milsym.codeplex.com/) 

I have experimented with milsymb-java/js. The interface is relatively straight forward and it can generate KML and GeoJSON. I have not looked at the implementation, but I know that the point symbology is  font based. 

Usually it only makes sense to draw control measures on a map, so the library should generate output that can be used with  OpenLayers and Leaflet. GeoJson is one option, but it does not support curved lines. milsymb-js/java solves this by converting curves to polylines. This works, but it requires many line segments to look good. 

SVG will look better, but you'll probably need to adjust the SVG output every time the map is zoomed in or out. Canvas is also an option.

**Comment by spatialillusions** [comment]
Thank you for your input. My idea at the moment is SVG, I have looked at the d3 layers examples that exists for both openlayers and Leaflet, so it's something like that I have in mind, but I keep thinking about it and see if I find some time to make some initial tests.

**Comment by szechyjs** [comment]
:+1:

**Comment by spatialillusions** [comment]
The initial plan is to support point symbols for tactical graphics. I'm adding functionality to inject new SIDC (so that you only will have tactical symbols if you want them and not otherwise) at the moment, and it will also require a rewrite of how the text labels are placed, but I got an idea for how to solv that.

**Comment by spatialillusions** [comment]
I have now added support injecting support for new SIDC and for non standard bounding boxes, this is the first step to supporting point graphics from tactical symbols. Next step is to be able to add new icon building blocks, and to be able to override text placements.

**Comment by spatialillusions** [comment]
All except two tactical points are now implemented, please have a look and give feedback. Since the size of the symbols isn't specified in the standard I had to improvise some. 
http://www.spatialillusions.com/milsymbol-dev/docs/milsymbol-2525c-tactical-points-svg.html
Does this work for you @szechyjs ?

**Comment by kjellmf** [comment]
Impressive work @spatialillusions! I'll have a look at them.

**Comment by spatialillusions** [comment]
Implementing something for graphics other than points will be done here:
https://github.com/spatialillusions/milgraphics
