### ISSUE TITLE
Canvas output

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#35]
This might be too much work, but I'm looking into canvas output. Please comment if you are interested in this or if I will be wasting my time.

**Comment by spatialillusions** [comment]
Initial tests up and running, so far so good. It's the icons that could be the tricky part, but I'm doing one part at a time. This is not drawing the SVG to a canvas, this is raw canvas instructions. :-)
<img width="1239" alt="screen shot 2015-12-09 at 23 17 57" src="https://cloud.githubusercontent.com/assets/8155542/11700646/6178e18e-9ecb-11e5-9a8a-665c7ff51eaf.png">

**Comment by spatialillusions** [comment]
Most of the icons are implemented now as well and I have had time to run some performance tests. The new drawinstructions that then is parsed to SVG or Canvas makes an over all performance hit, so we will loose some speed, but not that much when generating SVG. (1000 symbol speedtest on my computer went from 18milliseconds to 24milliseconds.) Generating Canvas is slower than SVG, and the speedtest gives an average of about 120milliseconds, not as fast as I would like, but still quite good.
A new setting for milsymbol will be introduced: MS.autoSVG, if this is set to true everything will work the same as today, and you can just keep using new versions of milsymbol, true is the default value. If MS.autoSVG is set to false it will not automatically generate SVG output and you will have to run symbol.asSVG() to get the SVG XML. There is also one method asCanvas() that will give you a canvas element with the drawn symbol, and processCanvasInstructions(ctx) where you can provide your own canvas for the symbol to be drawn on.

**Comment by bensleveritt** [comment]
Just to add that we've done SVG to canvas texture rendering, so this is actually very welcome.

Thanks!
