### ISSUE TITLE
Remove bower.json

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#43]
To reduce the maintenance the bower.json will be remove if there isn't any specific requests to keep it.

**Comment by okwolf** [comment]
Will this still allow adding milsymbol to our own project's bower.json with `"milsymbol": "0.5.6"` for example?

**Comment by spatialillusions** [comment]
I just wasn't sure if anyone was using bower, or if all just were using npm, but since you are using bower I will keep the file and everything should work as usual.

**Comment by okwolf** [comment]
Thanks! Since you don't have any dependencies on other libraries hopefully the only overhead of keeping bower.json is updating the version number. 😉
