### ISSUE TITLE
Add support for JavaScript modules

### ISSUE THREAD

**Issue by kjellmf** [spatialillusions/milsymbol#46]
I'm currently brushing up on my javascript skills and I'm trying to build a simple web application using the latest "state of the art" tools like npm, Typescript and  webpack/browserify. I also want to use milsymbol as part of the project, but I've run into some problems integrating it with webpack and browserify. The reason for this is that webpack interprets  milsymbol as CommonJS module and expects it to export variables and functions. Something like this:

`module.exports = MS;`

The problem is that milsymbol does not automatically make `MS` a global variable. This is usually a good thing, but when I use a tool like webpack, it puts milsymbol inside a function scope, so that the `MS` is not available outside of this scope. 

One workaround I found was to add something like this to milsymbol.js (code borrowed from Leaflet):

```
// Code from the Leaflet project:

if (typeof module === 'object' && typeof module.exports === 'object') {
	module.exports = MS;

} else if (typeof define === 'function' && define.amd) {
	define(MS);
}

// make MS a global variable
if (typeof window !== 'undefined') {
	window.MS = MS;
}
```
Another option may be to use browserify and browserify-shim and build a module friendly version of milsymbol.

Any thoughts on adding support for modern javascript module loaders?

**Comment by spatialillusions** [comment]
I think about it but it could be a good idea. Like you said it is usually a good idea to not populate global variables, but I also realize that this could be useful and I don't see any trouble with doing this in milsymbol as well. 

If you create a pull for this I will add it to milsymbol.

**Comment by kjellmf** [comment]
Thanks. I will experiment a bit first and submit a pull request when I better understand how the module loaders work.

**Comment by kjellmf** [comment]
See PR #47. I decided to only add the CommonJS part for now.
