### ISSUE TITLE
Create More Unit tests

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#57]
Milsymbol has grown quite a lot since the first version and it continues to grow. This has created a need for making some kind of automated unit test to make sure that edits don't break existing functionality. So far Mocha https://mochajs.org/ is the test framework that is considered, but if anyone has any other opinions I'm still open to suggestions.

**Comment by okwolf** [comment]
When will the work on unit tests begin?

**Comment by spatialillusions** [comment]
Since I'm doing all the coding by my self in nights and weekends there is at the moment no more plan for this than "after 1.0.0". I have done some looking into how to integrate automatic tests into GitHub, but at the moment I don't have specific plan. It is really one of those things where any help would be appreciated.

**Comment by okwolf** [comment]
I'd recommend working on this before #88, since having tests will make that refactor much easier to trust. Are you still ok with using Mocha?

**Comment by spatialillusions** [comment]
Mocha is fine by me.

**Comment by spatialillusions** [comment]
I made some small changes to the setup.js this weekend after modifying so that parseXML isn't a global anymore and moved to using window.btoa. Feel free to change them if anyone think I messed things up.

**Comment by okwolf** [comment]
@spatialillusions looks good to me!

**Comment by okwolf** [comment]
Take a look @ #122 for another baby step forward in testing behavior.

**Comment by okwolf** [comment]
@spatialillusions thanks for the merge! Please feel free to add more use cases you want coverage for. I'd like to make the syntax a bit less awkward and less brittle, but this should get the ball rolling.

**Comment by spatialillusions** [comment]
@okwolf It's me who should thank you! I was thinking about adding some more tests the other day, but I have a bit much to do at the moment, so I'm really glad that you fixed some things. 😀

**Comment by okwolf** [comment]
@spatialillusions I wouldn't go so far as to say I fixed anything, but at least we can know when things break 😉

An ideal next step would be to automate enough test coverage that you're comfortable shipping a release based on certain set of features working. From there maintenance/refactoring is much more enjoyable.

**Comment by spatialillusions** [comment]
Got an idea the other day. Under dev there is CSV files with sort of all SIDC... It should be possible to use them to test render all symbols and use isValid to check if the symbol is valid or not.

**Comment by okwolf** [comment]
@spatialillusions good idea! I had sat down and tried to write a generator for all valid SIDC the other day. That sample size quickly grows out of control so maybe it would be good to have some generative testing at some point also.

**Comment by okwolf** [comment]
Would having #157 help with this?

**Comment by spatialillusions** [comment]
Yes, that was sort of my idea. 
Then we need to think about if we want to render every symbol in the tests each time, but they should test more symbols than today.

**Comment by spatialillusions** [comment]
We should also look into moving to [jest](https://facebook.github.io/jest/) so since we now are using ES6 syntax internally. Maybe this should be in a separate case...

**Comment by okwolf** [comment]
> @spatialillusions We should also look into moving to jest so since we now are using ES6 syntax internally. Maybe this should be in a separate case...

See #164.

**Comment by spatialillusions** [comment]
As always @okwolf, you are awesome. This is fantastic and I got rid of the cache sharing problems that I had with mocha. Now each tests loads milsymbol individually like it should. 🙂 
I added a bunch of more test, so now everything in APP-6 D should be covered. 
(When I have fixed all symbols the test skipping I'm doing at the moment should be removed.)

**Comment by okwolf** [comment]
Great job with the additional coverage @spatialillusions! Up over 84% now in my report 💯 

I checked out the latest master, and it looks like we aren't skipping tests anymore, is that correct? It does take a bit longer to run the tests now, but hopefully that price is worth the confidence having those 2367 tests passing gives ✅ 

Good to close this issue now?

**Comment by spatialillusions** [comment]
Let's close this for now. I have fixed all the symbols that made it skip tests, so that is why they look good now. 🙂
My plan is to create similar tests for 2525B/C/D, so there will be quite a lot of test when that is done. But then we can be sure things are working as they should. (Actually found some previous unknown bugs when I did the APP-6 B tests.)
