### ISSUE TITLE
export module not available in npm package

### ISSUE THREAD

**Issue by jellebrouwer** [spatialillusions/milsymbol#59]
Could you please update the npm package? I created an angular module to implement your lib, but it needs this commit: https://github.com/spatialillusions/milsymbol/commit/743be4ab54a40f02e1aaee21bee4fb6a10e44bb9

**Comment by spatialillusions** [comment]
The initial plan was to wait with releasing a new version until APP6-D was implemented, but since that has been moved over and over again I will make a release that has the export module available. I just need to make some test checking the latest modifications I have done, so I didn't break anything.

**Comment by jellebrouwer** [comment]
Great

**Comment by spatialillusions** [comment]
How much in a hurry are you? I have done almost everything I need to be able to make a release, but I would like to make some code changes during the weekend, so would late weekend/early next week work for you?

**Comment by jellebrouwer** [comment]
No worries. Just pointed the dependency to GitHub, so no hurry at all. Appreciate your concern!

**Comment by mtomran** [comment]
I am also experiencing the same issue trying to load the lib with webpack.
Would appreciate it if you could update the npm package.

**Comment by spatialillusions** [comment]
There will be a new release during next week, just have to finish testing and update documentation.

**Comment by spatialillusions** [comment]
Milsymbol 0.6.0 is now released and published to NPM. 
https://github.com/spatialillusions/milsymbol/releases/tag/0.6.0
https://www.npmjs.com/package/milsymbol
Merry Christmas to everyone.
