### ISSUE TITLE
Update icons for Howitzer Self-propelled in APP-6(B) and MIL-2525C

### ISSUE THREAD

**Issue by FlemmingJ** [spatialillusions/milsymbol#72]
The icons for the sell-propelled howitzers are missing the horizontal lines indicating if they are light, medium or heavy.
From: http://www.spatialillusions.com/milsymbol/docs/milsymbol-APP6b-svg.html
![image](https://cloud.githubusercontent.com/assets/25221825/22104046/be0a18fc-de3d-11e6-8a26-277d700dabab.png)

From "APP-6(B) JOINT SYMBOLOGY JUNE 2008" page D-3-54
![image](https://cloud.githubusercontent.com/assets/25221825/22104277/b9e1047e-de3e-11e6-92bf-3fccdbad9906.png)

This affects:
APP-6(B)
HOWITZER LIGHT SELF-PROPELLED  1.X.3.2.1.8.1.1  S*G*EWHLS-*****
HOWITZER MEDIUM SELF-PROPELLED  1.X.3.2.1.8.2.1  S*G*EWHMS-*****
HOWITZER HEAVY SELF-PROPELLED  1.X.3.2.1.8.3.1  S*G*EWHHS-*****

MIL-STD-2525C
HOWITZER LIGHT SELF-PROPELLED  WAR.GRDTRK.EQT.WPN.HOW.LIT.SPD  S*G*EWHLS-*****
HOWITZER MEDIUM SELF-PROPELLED  WAR.GRDTRK.EQT.WPN.HOW.MDM.SPD  S*G*EWHMS-*****
HOWITZER HEAVY SELF-PROPELLED  WAR.GRDTRK.EQT.WPN.HOW.HVY.SPD  S*G*EWHHS-*****

**Comment by spatialillusions** [comment]
I have found the error and will correct the code within the next few days. 
Thank you very much for your report.
