### ISSUE TITLE
Implement Tactical Graphics

### ISSUE THREAD

**Issue by DragonbornSR** [spatialillusions/milsymbol#85]
Requesting tactical graphics (partially/commonly used), such as 2525C TACGRP.C2GM.SPL.LNE.AMB (ambush) etc.

**Comment by spatialillusions** [comment]
See #32, this is on the road map, but can't say when, at the moment the plan is to finish tactical points for app6b and release milsymbol 1.0.0 and the plan for that is before the end of mars if everything goes according to plan. 
If you have more complete list of tactical graphics you would like, please add issues for them at:
https://github.com/spatialillusions/milgraphics

(The plan is to start with Ambush and different types of axis of advance arrows.)
