### ISSUE TITLE
OL3 Example no longer match the latest released code

### ISSUE THREAD

**Issue by jkhoel** [spatialillusions/milsymbol#91]
ms.Symbol should be ms.symbol

**Comment by spatialillusions** [comment]
This was a change introduced in milsymbol 1.0, where MS.symbol was changed to ms.Symbol:
https://github.com/spatialillusions/milsymbol/blob/master/docs/README.md#mssymbolsidcoptions

It is also described under Added in the changelog:
https://github.com/spatialillusions/milsymbol/blob/master/CHANGELOG.md

And the change of this was to follow javascript coding convension that classes that should be initiated with `new` should have a name starting with a capital letter.

However, to avoid breaking existing code for people migrating from milsymbol 0.6 to 1.0, I kept the old naming as well.
https://github.com/spatialillusions/milsymbol/blob/master/build/milsymbol.js#L13

For most other backward compability functions it was possible to create a proxy function that solved this and logged an information message to the console, but this was not possible for the symbol object. (Didn't really understand why, but didn't dig into it.)

Please close this issue if this clarifies your questions, or add further information about why you think it should be changed.

**Comment by jkhoel** [comment]
Thank you for replying so quickly. I am fairly sure I tested ms.Symbol and it still broke my code. I am indeed migrating from 0.6 to 1.0, but I will test later today and close the issue accordingly.

Thank you for making such an amazing module

**Comment by spatialillusions** [comment]
You can see a live version of the sample here, and that is working and using the latest version of milsymbol.
http://spatialillusions.com/milsymbol/examples/example.html#openlayers3

Please let me know if you keep having any problems and I'll look into it.

**Comment by spatialillusions** [comment]
BTW, if you are able to give any details about what you are developing, don't hesitate to send me an email. I'm always interested in knowing what the library is used for and any improvements that can be done.

**Comment by jkhoel** [comment]
I have tested, and I can't really figure out why id did not work the first time. But it looks like the error was on my end!

My project is also on [github](https://github.com/jkhoel/dcs-mission-intel/) and is an out-of-game tool for a flightsim
